spring:
  webflux:
    base-path: /api
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  profiles:
    active: test
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 6.0.6
jwt:
  access-secret-key: "asfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasd"
external:
  battle:
    url: "https://dev.partyrun.online"
logging:
  level:
    root: info
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      uri: ${DB_URI}
    redis:
      url: redis://localhost:6379/0
jwt:
  access-secret-key: "asfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasdfasdfasdfaasfasdfasdfadfasd"
  access-expire-second: 1000000
external:
  battle:
    url: "https://dev.partyrun.online"
logging:
  level:
    root: info
---

spring:
  config:
    activate:
      on-profile: dev, prd
  data:
    mongodb:
      uri: ${DB_URI}
    redis:
      url: ${REDIS_URL}
jwt:
  access-secret-key: ${JWT_ACCESS_SECRET_KEY}
  access-expire-second: 1000000
external:
  battle:
    url: ${BATTLE_SERVICE_URL}
logging:
  level:
    root: info