:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

== Waiting
=== waiting 생성

operation::create-waiting[snippets='http-request,http-response']

=== waiting event stream 요청

operation::get-waiting-event[snippets='http-request,http-response']

=== waiting distance 값이 잘못 됨

operation::create-waiting-throw-distance-was-bad-value[snippets='http-request,http-response']
=== waiting 전체 삭제

operation::delete waiting[snippets='http-request,http-response']
== Matching

=== Matching 수락/거절 전송

operation::create-matching[snippets='http-request,http-response']

=== matching event stream 요청

operation::get-matching-event[snippets='http-request,http-response']


=== matching id를 통한 조회

operation::get-matching-by-id[snippets='http-request,http-response']

=== shutdown
operation::shutdown[snippets='http-request,http-response']

=== waiting event 취소
operation::cancel-waiting-event[snippets='http-request,http-response']

== Party

=== party 생성
operation::create-party[snippets='http-request,http-response']
=== party 참여
operation::join-party[snippets='http-request,http-response']
=== party running 시작
operation::start-party[snippets='http-request,http-response']
=== party 나가기
operation::quit-party[snippets='http-request,http-response']
=== 탐색한 party가 없으면 예외
operation::throw-exception-when-party-not-found[snippets='http-request,http-response']
